// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: entitis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_entitis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Conversion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	From          *Currency              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Currency              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Result        float64                `protobuf:"fixed64,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversion) Reset() {
	*x = Conversion{}
	mi := &file_entitis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversion) ProtoMessage() {}

func (x *Conversion) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversion.ProtoReflect.Descriptor instead.
func (*Conversion) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{1}
}

func (x *Conversion) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Conversion) GetFrom() *Currency {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Conversion) GetTo() *Currency {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Conversion) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CreateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_entitis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCurrencyRequest) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type ListCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesRequest) Reset() {
	*x = ListCurrenciesRequest{}
	mi := &file_entitis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesRequest) ProtoMessage() {}

func (x *ListCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{3}
}

type ListCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesResponse) Reset() {
	*x = ListCurrenciesResponse{}
	mi := &file_entitis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesResponse) ProtoMessage() {}

func (x *ListCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{4}
}

func (x *ListCurrenciesResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyRequest) Reset() {
	*x = GetCurrencyRequest{}
	mi := &file_entitis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyRequest) ProtoMessage() {}

func (x *GetCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrencyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyRequest) Reset() {
	*x = UpdateCurrencyRequest{}
	mi := &file_entitis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyRequest) ProtoMessage() {}

func (x *UpdateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCurrencyRequest) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type DeleteCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyRequest) Reset() {
	*x = DeleteCurrencyRequest{}
	mi := &file_entitis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyRequest) ProtoMessage() {}

func (x *DeleteCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCurrencyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateConversionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversionRequest) Reset() {
	*x = CreateConversionRequest{}
	mi := &file_entitis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversionRequest) ProtoMessage() {}

func (x *CreateConversionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversionRequest.ProtoReflect.Descriptor instead.
func (*CreateConversionRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{8}
}

func (x *CreateConversionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateConversionRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CreateConversionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ListConversionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversionsRequest) Reset() {
	*x = ListConversionsRequest{}
	mi := &file_entitis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversionsRequest) ProtoMessage() {}

func (x *ListConversionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversionsRequest.ProtoReflect.Descriptor instead.
func (*ListConversionsRequest) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{9}
}

type ListConversionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversions   []*Conversion          `protobuf:"bytes,1,rep,name=conversions,proto3" json:"conversions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversionsResponse) Reset() {
	*x = ListConversionsResponse{}
	mi := &file_entitis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversionsResponse) ProtoMessage() {}

func (x *ListConversionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entitis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversionsResponse.ProtoReflect.Descriptor instead.
func (*ListConversionsResponse) Descriptor() ([]byte, []int) {
	return file_entitis_proto_rawDescGZIP(), []int{10}
}

func (x *ListConversionsResponse) GetConversions() []*Conversion {
	if x != nil {
		return x.Conversions
	}
	return nil
}

var File_entitis_proto protoreflect.FileDescriptor

const file_entitis_proto_rawDesc = "" +
	"\n" +
	"\rentitis.proto\x12\x11CurrencyConverter\x1a\x1bgoogle/protobuf/empty.proto\"^\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\"\x9a\x01\n" +
	"\n" +
	"Conversion\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12/\n" +
	"\x04from\x18\x02 \x01(\v2\x1b.CurrencyConverter.CurrencyR\x04from\x12+\n" +
	"\x02to\x18\x03 \x01(\v2\x1b.CurrencyConverter.CurrencyR\x02to\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x01R\x06result\"P\n" +
	"\x15CreateCurrencyRequest\x127\n" +
	"\bcurrency\x18\x01 \x01(\v2\x1b.CurrencyConverter.CurrencyR\bcurrency\"\x17\n" +
	"\x15ListCurrenciesRequest\"U\n" +
	"\x16ListCurrenciesResponse\x12;\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x1b.CurrencyConverter.CurrencyR\n" +
	"currencies\"(\n" +
	"\x12GetCurrencyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"P\n" +
	"\x15UpdateCurrencyRequest\x127\n" +
	"\bcurrency\x18\x01 \x01(\v2\x1b.CurrencyConverter.CurrencyR\bcurrency\"+\n" +
	"\x15DeleteCurrencyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"U\n" +
	"\x17CreateConversionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\x18\n" +
	"\x16ListConversionsRequest\"Z\n" +
	"\x17ListConversionsResponse\x12?\n" +
	"\vconversions\x18\x01 \x03(\v2\x1d.CurrencyConverter.ConversionR\vconversions2\xd1\x03\n" +
	"\x0fCurrencyService\x12W\n" +
	"\x0eCreateCurrency\x12(.CurrencyConverter.CreateCurrencyRequest\x1a\x1b.CurrencyConverter.Currency\x12Q\n" +
	"\vGetCurrency\x12%.CurrencyConverter.GetCurrencyRequest\x1a\x1b.CurrencyConverter.Currency\x12W\n" +
	"\x0eUpdateCurrency\x12(.CurrencyConverter.UpdateCurrencyRequest\x1a\x1b.CurrencyConverter.Currency\x12R\n" +
	"\x0eDeleteCurrency\x12(.CurrencyConverter.DeleteCurrencyRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x0eListCurrencies\x12(.CurrencyConverter.ListCurrenciesRequest\x1a).CurrencyConverter.ListCurrenciesResponse2\xdc\x01\n" +
	"\x11ConversionService\x12]\n" +
	"\x10CreateConversion\x12*.CurrencyConverter.CreateConversionRequest\x1a\x1d.CurrencyConverter.Conversion\x12h\n" +
	"\x0fListConversions\x12).CurrencyConverter.ListConversionsRequest\x1a*.CurrencyConverter.ListConversionsResponseB)Z'currency-converter/internal/proto;protob\x06proto3"

var (
	file_entitis_proto_rawDescOnce sync.Once
	file_entitis_proto_rawDescData []byte
)

func file_entitis_proto_rawDescGZIP() []byte {
	file_entitis_proto_rawDescOnce.Do(func() {
		file_entitis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entitis_proto_rawDesc), len(file_entitis_proto_rawDesc)))
	})
	return file_entitis_proto_rawDescData
}

var file_entitis_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_entitis_proto_goTypes = []any{
	(*Currency)(nil),                // 0: CurrencyConverter.Currency
	(*Conversion)(nil),              // 1: CurrencyConverter.Conversion
	(*CreateCurrencyRequest)(nil),   // 2: CurrencyConverter.CreateCurrencyRequest
	(*ListCurrenciesRequest)(nil),   // 3: CurrencyConverter.ListCurrenciesRequest
	(*ListCurrenciesResponse)(nil),  // 4: CurrencyConverter.ListCurrenciesResponse
	(*GetCurrencyRequest)(nil),      // 5: CurrencyConverter.GetCurrencyRequest
	(*UpdateCurrencyRequest)(nil),   // 6: CurrencyConverter.UpdateCurrencyRequest
	(*DeleteCurrencyRequest)(nil),   // 7: CurrencyConverter.DeleteCurrencyRequest
	(*CreateConversionRequest)(nil), // 8: CurrencyConverter.CreateConversionRequest
	(*ListConversionsRequest)(nil),  // 9: CurrencyConverter.ListConversionsRequest
	(*ListConversionsResponse)(nil), // 10: CurrencyConverter.ListConversionsResponse
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_entitis_proto_depIdxs = []int32{
	0,  // 0: CurrencyConverter.Conversion.from:type_name -> CurrencyConverter.Currency
	0,  // 1: CurrencyConverter.Conversion.to:type_name -> CurrencyConverter.Currency
	0,  // 2: CurrencyConverter.CreateCurrencyRequest.currency:type_name -> CurrencyConverter.Currency
	0,  // 3: CurrencyConverter.ListCurrenciesResponse.currencies:type_name -> CurrencyConverter.Currency
	0,  // 4: CurrencyConverter.UpdateCurrencyRequest.currency:type_name -> CurrencyConverter.Currency
	1,  // 5: CurrencyConverter.ListConversionsResponse.conversions:type_name -> CurrencyConverter.Conversion
	2,  // 6: CurrencyConverter.CurrencyService.CreateCurrency:input_type -> CurrencyConverter.CreateCurrencyRequest
	5,  // 7: CurrencyConverter.CurrencyService.GetCurrency:input_type -> CurrencyConverter.GetCurrencyRequest
	6,  // 8: CurrencyConverter.CurrencyService.UpdateCurrency:input_type -> CurrencyConverter.UpdateCurrencyRequest
	7,  // 9: CurrencyConverter.CurrencyService.DeleteCurrency:input_type -> CurrencyConverter.DeleteCurrencyRequest
	3,  // 10: CurrencyConverter.CurrencyService.ListCurrencies:input_type -> CurrencyConverter.ListCurrenciesRequest
	8,  // 11: CurrencyConverter.ConversionService.CreateConversion:input_type -> CurrencyConverter.CreateConversionRequest
	9,  // 12: CurrencyConverter.ConversionService.ListConversions:input_type -> CurrencyConverter.ListConversionsRequest
	0,  // 13: CurrencyConverter.CurrencyService.CreateCurrency:output_type -> CurrencyConverter.Currency
	0,  // 14: CurrencyConverter.CurrencyService.GetCurrency:output_type -> CurrencyConverter.Currency
	0,  // 15: CurrencyConverter.CurrencyService.UpdateCurrency:output_type -> CurrencyConverter.Currency
	11, // 16: CurrencyConverter.CurrencyService.DeleteCurrency:output_type -> google.protobuf.Empty
	4,  // 17: CurrencyConverter.CurrencyService.ListCurrencies:output_type -> CurrencyConverter.ListCurrenciesResponse
	1,  // 18: CurrencyConverter.ConversionService.CreateConversion:output_type -> CurrencyConverter.Conversion
	10, // 19: CurrencyConverter.ConversionService.ListConversions:output_type -> CurrencyConverter.ListConversionsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_entitis_proto_init() }
func file_entitis_proto_init() {
	if File_entitis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entitis_proto_rawDesc), len(file_entitis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_entitis_proto_goTypes,
		DependencyIndexes: file_entitis_proto_depIdxs,
		MessageInfos:      file_entitis_proto_msgTypes,
	}.Build()
	File_entitis_proto = out.File
	file_entitis_proto_goTypes = nil
	file_entitis_proto_depIdxs = nil
}
