// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/entities.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Conversion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	From          *Currency              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Currency              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Result        float64                `protobuf:"fixed64,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversion) Reset() {
	*x = Conversion{}
	mi := &file_proto_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversion) ProtoMessage() {}

func (x *Conversion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversion.ProtoReflect.Descriptor instead.
func (*Conversion) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Conversion) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Conversion) GetFrom() *Currency {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Conversion) GetTo() *Currency {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Conversion) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CreateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_proto_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCurrencyRequest) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type ListCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesResponse) Reset() {
	*x = ListCurrenciesResponse{}
	mi := &file_proto_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesResponse) ProtoMessage() {}

func (x *ListCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{3}
}

func (x *ListCurrenciesResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type CreateConversionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversionRequest) Reset() {
	*x = CreateConversionRequest{}
	mi := &file_proto_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversionRequest) ProtoMessage() {}

func (x *CreateConversionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversionRequest.ProtoReflect.Descriptor instead.
func (*CreateConversionRequest) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConversionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateConversionRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CreateConversionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ListConversionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversions   []*Conversion          `protobuf:"bytes,1,rep,name=conversions,proto3" json:"conversions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversionsResponse) Reset() {
	*x = ListConversionsResponse{}
	mi := &file_proto_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversionsResponse) ProtoMessage() {}

func (x *ListConversionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversionsResponse.ProtoReflect.Descriptor instead.
func (*ListConversionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_entities_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversionsResponse) GetConversions() []*Conversion {
	if x != nil {
		return x.Conversions
	}
	return nil
}

var File_proto_entities_proto protoreflect.FileDescriptor

const file_proto_entities_proto_rawDesc = "" +
	"\n" +
	"\x14proto/entities.proto\x12\x11CurrencyConverter\x1a\x1bgoogle/protobuf/empty.proto\"^\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\"\x9a\x01\n" +
	"\n" +
	"Conversion\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12/\n" +
	"\x04from\x18\x02 \x01(\v2\x1b.CurrencyConverter.CurrencyR\x04from\x12+\n" +
	"\x02to\x18\x03 \x01(\v2\x1b.CurrencyConverter.CurrencyR\x02to\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x01R\x06result\"P\n" +
	"\x15CreateCurrencyRequest\x127\n" +
	"\bcurrency\x18\x01 \x01(\v2\x1b.CurrencyConverter.CurrencyR\bcurrency\"U\n" +
	"\x16ListCurrenciesResponse\x12;\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x1b.CurrencyConverter.CurrencyR\n" +
	"currencies\"U\n" +
	"\x17CreateConversionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"Z\n" +
	"\x17ListConversionsResponse\x12?\n" +
	"\vconversions\x18\x01 \x03(\v2\x1d.CurrencyConverter.ConversionR\vconversions2\xd4\x02\n" +
	"\x0fCurrencyService\x12W\n" +
	"\x0eCreateCurrency\x12(.CurrencyConverter.CreateCurrencyRequest\x1a\x1b.CurrencyConverter.Currency\x12G\n" +
	"\vGetCurrency\x12\x1b.CurrencyConverter.Currency\x1a\x1b.CurrencyConverter.Currency\x12J\n" +
	"\x0eUpdateCurrency\x12\x1b.CurrencyConverter.Currency\x1a\x1b.CurrencyConverter.Currency\x12S\n" +
	"\x0eListCurrencies\x12\x16.google.protobuf.Empty\x1a).CurrencyConverter.ListCurrenciesResponse2\xc9\x01\n" +
	"\x11ConversionService\x12]\n" +
	"\x10CreateConversion\x12*.CurrencyConverter.CreateConversionRequest\x1a\x1d.CurrencyConverter.Conversion\x12U\n" +
	"\x0fListConversions\x12\x16.google.protobuf.Empty\x1a*.CurrencyConverter.ListConversionsResponseB)Z'currency-converter/internal/proto;protob\x06proto3"

var (
	file_proto_entities_proto_rawDescOnce sync.Once
	file_proto_entities_proto_rawDescData []byte
)

func file_proto_entities_proto_rawDescGZIP() []byte {
	file_proto_entities_proto_rawDescOnce.Do(func() {
		file_proto_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_entities_proto_rawDesc), len(file_proto_entities_proto_rawDesc)))
	})
	return file_proto_entities_proto_rawDescData
}

var file_proto_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_entities_proto_goTypes = []any{
	(*Currency)(nil),                // 0: CurrencyConverter.Currency
	(*Conversion)(nil),              // 1: CurrencyConverter.Conversion
	(*CreateCurrencyRequest)(nil),   // 2: CurrencyConverter.CreateCurrencyRequest
	(*ListCurrenciesResponse)(nil),  // 3: CurrencyConverter.ListCurrenciesResponse
	(*CreateConversionRequest)(nil), // 4: CurrencyConverter.CreateConversionRequest
	(*ListConversionsResponse)(nil), // 5: CurrencyConverter.ListConversionsResponse
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_proto_entities_proto_depIdxs = []int32{
	0,  // 0: CurrencyConverter.Conversion.from:type_name -> CurrencyConverter.Currency
	0,  // 1: CurrencyConverter.Conversion.to:type_name -> CurrencyConverter.Currency
	0,  // 2: CurrencyConverter.CreateCurrencyRequest.currency:type_name -> CurrencyConverter.Currency
	0,  // 3: CurrencyConverter.ListCurrenciesResponse.currencies:type_name -> CurrencyConverter.Currency
	1,  // 4: CurrencyConverter.ListConversionsResponse.conversions:type_name -> CurrencyConverter.Conversion
	2,  // 5: CurrencyConverter.CurrencyService.CreateCurrency:input_type -> CurrencyConverter.CreateCurrencyRequest
	0,  // 6: CurrencyConverter.CurrencyService.GetCurrency:input_type -> CurrencyConverter.Currency
	0,  // 7: CurrencyConverter.CurrencyService.UpdateCurrency:input_type -> CurrencyConverter.Currency
	6,  // 8: CurrencyConverter.CurrencyService.ListCurrencies:input_type -> google.protobuf.Empty
	4,  // 9: CurrencyConverter.ConversionService.CreateConversion:input_type -> CurrencyConverter.CreateConversionRequest
	6,  // 10: CurrencyConverter.ConversionService.ListConversions:input_type -> google.protobuf.Empty
	0,  // 11: CurrencyConverter.CurrencyService.CreateCurrency:output_type -> CurrencyConverter.Currency
	0,  // 12: CurrencyConverter.CurrencyService.GetCurrency:output_type -> CurrencyConverter.Currency
	0,  // 13: CurrencyConverter.CurrencyService.UpdateCurrency:output_type -> CurrencyConverter.Currency
	3,  // 14: CurrencyConverter.CurrencyService.ListCurrencies:output_type -> CurrencyConverter.ListCurrenciesResponse
	1,  // 15: CurrencyConverter.ConversionService.CreateConversion:output_type -> CurrencyConverter.Conversion
	5,  // 16: CurrencyConverter.ConversionService.ListConversions:output_type -> CurrencyConverter.ListConversionsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_entities_proto_init() }
func file_proto_entities_proto_init() {
	if File_proto_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_entities_proto_rawDesc), len(file_proto_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_entities_proto_goTypes,
		DependencyIndexes: file_proto_entities_proto_depIdxs,
		MessageInfos:      file_proto_entities_proto_msgTypes,
	}.Build()
	File_proto_entities_proto = out.File
	file_proto_entities_proto_goTypes = nil
	file_proto_entities_proto_depIdxs = nil
}
